import{useEffect,useRef,useState}from'react';import{getClaimEmails,sendClaimEmail,type EmailLog}from'./emailApi';import type{Generation}from'./types';import'./email.css';
const escapeHtml=(value:string)=>value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const toHtml=(value:string)=>value.split(/\n{2,}/).map(part=>`<p>${escapeHtml(part).replace(/\n/g,'<br>')}</p>`).join('');
export default function EmailComposer({claimId,generation,customerName,customerId}:{claimId:string;generation:Generation;customerName:string;customerId:string}){const editor=useRef<HTMLDivElement>(null);const[subject,setSubject]=useState(`Suivi de votre sinistre ${claimId}`),[html,setHtml]=useState(()=>toHtml(generation.generatedContent||'')),[preview,setPreview]=useState(false),[sending,setSending]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[emails,setEmails]=useState<EmailLog[]>([]);const recipient=`${customerId.toLowerCase()}@demo.astree.local`;
useEffect(()=>{const next=toHtml(generation.generatedContent||'');setHtml(next);if(editor.current)editor.current.innerHTML=next},[generation.generationId]);
useEffect(()=>{getClaimEmails(claimId).then(setEmails).catch(()=>{})},[claimId]);
function format(command:string){document.execCommand(command);editor.current?.focus();setHtml(editor.current?.innerHTML||'')}
async function send(){setError('');setMessage('');if(!subject.trim()||!html.trim()){setError('L’objet et le contenu sont obligatoires.');return}if(!window.confirm(`Confirmer l’envoi de cet e-mail de démonstration pour ${customerName} ?`))return;setSending(true);try{const sent=await sendClaimEmail(claimId,{clientRequestId:crypto.randomUUID(),generationId:generation.generationId,subject:subject.trim(),bodyHtml:html,confirmation:true});setEmails(current=>[sent,...current]);setMessage(`E-mail envoyé avec succès dans Mailtrap (${sent.actualRecipientEmail}).`)}catch(e){setError((e as Error).message)}finally{setSending(false)}}
return <section className="emailComposer"><div className="emailTitle"><div><small>E-MAIL DE DÉMONSTRATION</small><h2>Préparer l’e-mail à l’assuré</h2><p>Le message sera intercepté par Mailtrap. Aucun envoi réel n’est effectué.</p></div><span>Mailtrap Sandbox</span></div><div className="emailFields"><label>Destinataire<input value={`${customerName} — ${recipient}`} readOnly/></label><label>Objet<input value={subject} onChange={e=>setSubject(e.target.value)} maxLength={200}/></label></div><div className="editorBox"><div className="toolbar" aria-label="Mise en forme"><button type="button" onClick={()=>format('bold')} title="Gras"><b>G</b></button><button type="button" onClick={()=>format('italic')} title="Italique"><i>I</i></button><button type="button" onClick={()=>format('underline')} title="Souligné"><u>S</u></button><button type="button" onClick={()=>format('insertUnorderedList')} title="Liste">• Liste</button><button type="button" onClick={()=>format('undo')} title="Annuler">↶</button><button type="button" onClick={()=>format('redo')} title="Rétablir">↷</button></div><div ref={editor} className="wysiwyg" contentEditable suppressContentEditableWarning onInput={e=>setHtml(e.currentTarget.innerHTML)} dangerouslySetInnerHTML={{__html:html}}/></div><div className="emailActions"><button type="button" className="secondaryAction" onClick={()=>setPreview(!preview)}>{preview?'Fermer l’aperçu':'Prévisualiser'}</button><button type="button" className="sendAction" disabled={sending} onClick={send}>{sending?'Envoi en cours…':'Envoyer vers Mailtrap'}</button></div>{preview&&<div className="mailPreview"><div><b>À :</b> {recipient}</div><div><b>Objet :</b> {subject}</div><article dangerouslySetInnerHTML={{__html:html}}/></div>}{message&&<p className="emailSuccess">✓ {message}</p>}{error&&<p className="emailError">{error}</p>}<div className="emailHistory"><h3>Historique des e-mails</h3>{emails.length?emails.map(item=><div key={item.emailId}><span className={item.status}>{item.status==='sent'?'Envoyé':item.status==='failed'?'Échec':'En cours'}</span><b>{item.subject}</b><small>{new Intl.DateTimeFormat('fr-TN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.createdAt))}</small></div>):<p>Aucun e-mail envoyé pour ce dossier.</p>}</div></section>}
